### ISSUE TITLE
Client error '404 Not Found' for url

### ISSUE THREAD

**Issue by WonderCRM** [Ground-Zerro/DomainMapper#37]
Есть проблемка

```
Traceback (most recent call last):
  File "c:\Python\DomainMapper\main_.py", line 652, in <module>
    asyncio.run(main())
  File "C:\Python\IDE\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python\IDE\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\IDE\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Python\DomainMapper\main_.py", line 615, in main
    dns_names = await load_dns_names(url_or_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python\DomainMapper\main_.py", line 230, in load_dns_names
    response.raise_for_status()
  File "c:\Python\DomainMapper\venv\Lib\site-packages\httpx\_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://raw.githubusercontent.com/Ground-Zerro/DomainMapper/main/platforms/dns-github-%D0%A1%D0%83opilot.txt'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
sys:1: RuntimeWarning: coroutine 'resolve_dns' was never awaited
```

Решение:

```
async def load_dns_names(url_or_file):
    if url_or_file.startswith("http"):
        async with httpx.AsyncClient() as client:
            try:
                response = await client.get(url_or_file)
                response.raise_for_status()
                return response.text.splitlines()
            except httpx.HTTPStatusError as e:
                print(f"Ошибка при загрузке DNS имен: {e}")
                return []
    else:
        # Локальный файл
        with open(url_or_file, 'r', encoding='utf-8') as file:
            return file.read().splitlines()
```

**Comment by Ground-Zerro** [comment]
Спасибо.
Добавил.

Есть еще места без обработки исключений.
Рассудил, что код работает, а ошибки связанны только с неверно указанными файлами, их содержимым, недоступностью или кодировкой и это в любом случае придётся решать пользователю.
